version: '3'

services:
  backup:
    container_name: docker-volume-backup
    image: offen/docker-volume-backup:v2
    env_file:
      - ".env"
    environment:
      BACKUP_CRON_EXPRESSION: "0 3 * * *" #every day at 03.00 "0 3 * * *"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      AWS_ENDPOINT_PROTO: "http"
      # NOTIFICATION_URLS: "smtp://${SMTP_USERNAME}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT}/?fromAddress=${SMTP_FROM}&toAddresses=${TO_SENT_EMAIL}"
      NOTIFICATION_URLS: "telegram://${TELEGRAM_TOKEN}@telegram?chats=${TELEGRAM_USER_ID}"
      # NOTIFICATION_LEVEL: "info"
      BACKUP_STOP_CONTAINER_LABEL: stopservice
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - backup:/backup/
      - transmission:/backup/transmission:ro
      - vaultwarden_vaultwarden:/backup/vaultwarden:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  backup:
    name: backup

  transmission:
    name: transmission_transmission
    external: true

  vaultwarden_vaultwarden:
    name: vaultwarden_vaultwarden
    external: true
